# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        none

# Setup
title:            Victor Gan
tagline:          Website
url:              http://victorgan.github.io
paginate:         1
baseurl:          /
author:
  name:           Victor Gan
  url:            https://vgan.ca
  email:          victorgan@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/victorgan/victorgan.github.io.git

# This is the list of pages to include in the header of the website.
# pages_list:       
  # About:    '/about.html'
  # Feed:     '/atom.xml'

# Should enable comments?
comments: true

# when calling {{ post.excerpt }}, will only return until this symbol
excerpt_separator: <!--end excerpt-->
